### ISSUE TITLE
Unable to install?

### ISSUE THREAD

**Issue by tomgillett** [octoberrain/all#1]
I was keen to use this package in my base install having seen it announced [here](https://octobercms.com/support/article/rn-27#new-october-all). However, it seems to require packages / versions that aren't available on [packagist.org](https://packagist.org/packages/october/all):

- `october/backend`, `october/cms` and `october/system` are not available ^2.0 
- `october/editor` and `october/media` are not available at all

Have I missed something, or is it impossible to install this package?

**Comment by tomgillett** [comment]
For anyone else struggling in the future, it turns out I was missing something! 

My Composer file was messed up, and was failing to access the packages from gateway.octobercms.com.

**Comment by daftspunk** [comment]
Yes, this is correct, some of the required packages here transition from public → private and the gateway definition is needed. Glad you got it sorted!
